### ISSUE TITLE
How to bend the Flex PCB?

### ISSUE THREAD

**Issue by Dakkaron** [arturo182/pmod_bbq10_keyboard#1]
I am trying to build something similar (a keyboard attachment for my phone) but I can't figure out how to safely bend the flex PCB in a way that I have the connector somewhere else than on the phone screen.

How did you move the connector to where you put it?

**Comment by arturo182** [comment]
It's quite hard to explain but hopefully, these photos show it well enough. The flex is bent onto itself quite harshly, but the keyboard and the flex are held in place with double-sided tape so they are not moving at all.

![image](https://user-images.githubusercontent.com/249082/140533964-32a24fcd-7b9f-48e1-adb4-d1cbb54727db.png)
![image](https://user-images.githubusercontent.com/249082/140533982-4113b8b4-ef30-460e-8218-21962aff870c.png)
![image](https://user-images.githubusercontent.com/249082/140533998-2492240b-4b6c-4239-90af-38aa849898b9.png)


I have another board using this keyboard (https://github.com/solderparty/keyboard_featherwing_hw) and since that one is larger, there is no need to bend the flex, I follow the natural shape of the flex, just go from one side of the board to the other and put a connector where it ends:
![image](https://user-images.githubusercontent.com/249082/140533552-4c98d58e-6dc7-4b89-8482-e1ce270f0368.png)

**Comment by Dakkaron** [comment]
Awesome! Thanks for the great description and the pictures!
My solution will probably have even less space than your original one, so I'd probably take the same route.
I just couldn't figure out whether the flex PCB would survive such a harsh bend, and wanted to take your work as an example.

Thanks a lot!
